### ISSUE TITLE
Translucency on tooltip intermittently

### ISSUE THREAD

**Issue by BenjaminMichaelis** [IntelliTect/EssentialCSharp.Web#630]
https://essentialcsharp.com/defining-custom-exceptions

https://github.com/user-attachments/assets/158d39a5-7f8d-447c-95ab-451b4ff6ee00

**Comment by Joshua-Lester3** [comment]
On a smaller screen size, the bullet points also are above the page turn buttons. It's hard to see, but still there:
<img width="466" alt="image" src="https://github.com/user-attachments/assets/440ac990-d210-4f29-a9d9-0de034f3fe27">
